if(${ARCH} STREQUAL not_set)
    message(STATUS "macOS Architecture not set, using x86_64 as default.")
    SET(CMAKE_OSX_ARCHITECTURES "x86_64")
else()
    if(${ARCH} STREQUAL x86_64 OR ${ARCH} STREQUAL arm64)
        set(CMAKE_OSX_ARCHITECTURES "${ARCH}")
    else()
        message(FATAL_ERROR "Invalid CMAKE_OSX_ARCHITECTURES: ARCH=${ARCH}.")
    endif()
endif()

set(CMAKE_SKIP_BUILD_RPATH TRUE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_INSTALL_RPATH "@loader_path")

